# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  PHP: true
exclude_paths:
-application/third_party/*
-application/tests/*
-public/assets/javascripts/jquery*
-public/assets/javascripts/bootstrap.js
-public/assets/stylesheets/bootstrap.css